name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  BOT_IMAGE: ${{ github.repository_owner }}/nichmusik-bot
  LAVALINK_IMAGE: ${{ github.repository_owner }}/nichmusik-lavalink

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Metadata: Lavalink
      - name: Extract Docker metadata (lavalink)
        id: meta_lavalink
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ env.REGISTRY }}/${{ env.LAVALINK_IMAGE }}
          flavor: |
            latest=true
          tags: |
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}

      # Metadata: Bot
      - name: Extract Docker metadata (bot)
        id: meta_bot
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ env.REGISTRY }}/${{ env.BOT_IMAGE }}
          flavor: |
            latest=true
          tags: |
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}

      - name: Build and push Lavalink Docker image
        id: build-lavalink
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: ./lavalink
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_lavalink.outputs.tags }}
          labels: ${{ steps.meta_lavalink.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Bot Docker image
        id: build-bot
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_bot.outputs.tags }}
          labels: ${{ steps.meta_bot.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker images
        if: ${{ github.event_name != 'pull_request' }}
        env:
          LAVALINK_TAGS: ${{ steps.meta_lavalink.outputs.tags }}
          BOT_TAGS: ${{ steps.meta_bot.outputs.tags }}
          LAVALINK_DIGEST: ${{ steps.build-lavalink.outputs.digest }}
          BOT_DIGEST: ${{ steps.build-bot.outputs.digest }}
        run: |
          echo "${LAVALINK_TAGS}" | xargs -I {} cosign sign --yes {}@${LAVALINK_DIGEST}
          echo "${BOT_TAGS}"      | xargs -I {} cosign sign --yes {}@${BOT_DIGEST}
